apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-html-deployment
spec:
  replicas: 1
  selector:clear
    matchLabels:
      app: apache-html-app
  template:
    metadata:
      labels:
        app: apache-html-app
    spec:
      containers:
      - name: apache-container
        image: my-apache-html-app:latest  # Use the local Docker image
        imagePullPolicy: Never  # Add this line if necessary

        ports:
        - containerPort: 80  # The container listens on port 80
---
apiVersion: v1
kind: Service
metadata:
  name: apache-html-service
spec:
  selector:
    app: apache-html-app
  ports:
    - protocol: TCP
      port: 80  # Port exposed externally
      targetPort: 80  # Port inside the container
  type: LoadBalancer  # Exposes the service externally on localhost (for Docker Desktop)
